Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0692dea0a2f8a1b35 # Replace with your desired Amazon Machine Image (AMI) ID
      Tags:
        - Key: Name
          Value: my-ec2-instance
      SubnetId: subnet-06b88f16ad53d7f10
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1> Welcome to monitoring demo </h1>" > /var/www/html/index.html
